theme: jekyll-theme-hacker
markdown: kramdown
title: RSI "Progress Tracker" Deltas
description: Lists and displays detected changes on the RSI "Progress Tracker"
defaults:
  - scope:
      path: "data"
    values:
      csv: true
