### Site metadata

title: ShinyTracker
description: Lists and displays detected changes on the RSI "Progress Tracker"

### Build settings

url: https://shinyhobo.github.io

theme: jekyll-theme-hacker
markdown: kramdown

incremental: true

defaults:
  - scope:
      path: "data"
    values:
      csv: true
  - scope:
      path: "snapshots"
    values:
      json: true
  - scope:
      path: "*.md"
    values:
      layout: page

include:
  - tests/database-browser

exclude:
  - docs/
  - Makefile
  - README.md
  - Gemfile
  - Gemfile.lock
  - tests/database-browser-src

plugins:
  - jekyll-sitemap

gems:
  - jekyll-paginate-v2

#permalink: /:year/:month/:day/:title.html

pagination:
  enabled: true
  per_page: 10
  offset: 0
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 5
    after: 5

feed:
  post_limit: 2
  excerpt_only: true