theme: jekyll-theme-hacker
markdown: kramdown
title: ShinyTracker
description: Lists and displays detected changes on the RSI "Progress Tracker"
defaults:
  - scope:
      path: "data"
    values:
      csv: true
  - scope:
      path: "snapshots"
    values:
      json: true
