name: Custom Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: actions/jekyll-build-pages@1.0.2
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: actions/deploy-pages@1.0.1
